### ISSUE TITLE
Where is the page to display ?

### ISSUE THREAD

**Issue by theofruitrouge** [GittiHab/HTML-Secure#1]
Hi,

I constantly get the 404. Where do I put my « protected » code ?

**Comment by GittiHab** [comment]
Hi @theofruitrouge,
if you look at the `.htaccess` file, you will see that it simply redirects all requests to `.html` files to the `index.php` file. Therefore, it doesn't matter where your files are – as long as the files of "HTML-Secure" are in the same or parent folder.

If you have other files than `html` files you can add these to the htaccess file and you might need to modify `index.php` accordingly.

To open your page simply type in the path to your html file as you would usually, e.g., `domain.com/index.html`.

**Comment by theofruitrouge** [comment]
Thank you very much for the help.

Haven't thought about looking in the .htaccess

**Comment by GittiHab** [comment]
OK, no problem 👍
